### ISSUE TITLE
This crate is broken

### ISSUE THREAD

**Issue by shisoft** [alexcrichton/futures-await#113]
After upgrading to 1.34.0-nightly, this compiler have following message and stopped. 
```
error[E0599]: no method named `resume` found for type `T` in the current scope
   --> /Users/shisoft/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-await-0.1.1/src/lib.rs:120:35
    |
120 |             match unsafe { self.0.resume() } {
    |                                   ^^^^^^
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `resume`, perhaps you need to implement it:
            candidate #1: `std::ops::Generator`

error[E0599]: no method named `resume` found for type `T` in the current scope
   --> /Users/shisoft/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-await-0.1.1/src/lib.rs:140:37
    |
140 |             match unsafe { self.gen.resume() } {
    |                                     ^^^^^^
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `resume`, perhaps you need to implement it:
            candidate #1: `std::ops::Generator`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `futures-await`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I know this crate is under maintaining mode. Just asking suggestions for migrate to rust built-in features to move on.
Thanks

**Comment by vorot93** [comment]
#112
