### ISSUE TITLE
Fails to compile on 1.27.0-nightly

### ISSUE THREAD

**Issue by colinbankier** [alexcrichton/futures-await#102]
Apologies if I'm confused and just doing it wrong.
I am trying to compile with rust 1.27.0-nightly following the steps from the readme, but get:
```
rustup update nightly
rustup default nightly
cargo +nightly build
```

```
   Compiling proc-macro2 v0.3.8
error[E0433]: failed to resolve. Could not find `Op` in `proc_macro`
   --> /home/colin/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.8/src/unstable.rs:131:42
    |
131 |                 let mut op = proc_macro::Op::new(tt.op(), spacing);
    |                                          ^^ Could not find `Op` in `proc_macro`

error[E0433]: failed to resolve. Could not find `Term` in `proc_macro`
   --> /home/colin/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.8/src/unstable.rs:446:59
    |
446 |             Span::Nightly(s) => Term::Nightly(proc_macro::Term::new(string, s)),
    |                                                           ^^^^ Could not find `Term` in `proc_macro`

error[E0412]: cannot find type `Term` in module `proc_macro`
   --> /home/colin/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.8/src/unstable.rs:439:25
    |
439 |     Nightly(proc_macro::Term),
    |                         ^^^^ not found in `proc_macro`
help: possible candidates are found in other modules, you can import them into scope
    |
3   | use Term;
    |
3   | use imp::Term;
    |
3   | use stable::Term;

```
Older releases of rust nightly had similar errors. Am I missing something simple?

**Comment by thomasnaudin** [comment]
Same problem here after updating to latest nightly.

**Comment by alex** [comment]
I haven't dived too deep on this, but I suspect proc-macro 0.4.1 resolves this.

**Comment by withoutboats** [comment]
Yea seems like just some proc-macro churn, would appreciate a PR because I'm not sure when I'll be able to look into it. :)

**Comment by colinbankier** [comment]
This seems blocked until some dependencies update their `proc-macro2` version - mainly `quote` and `serde-derive` from what I could tell.

**Comment by golddranks** [comment]
The workaround at the moment is to use older nightly. I succeed in compiling with 2018-05-16.

`Quote` has now released version 0.6 which should work with the newer nightlies.

**Comment by golddranks** [comment]
Sent a PR: https://github.com/alexcrichton/futures-await/pull/104 It doesn't pass tests yet because something about declaring the `'static` lifetimes has changed. Help appreciated!

**Comment by withoutboats** [comment]
futures-await-async-macro has been fixed in 0.1.4, update your dependency with cargo update -p futures-await-async-macro :) (you might also need to update your nightly)
