### ISSUE TITLE
Another crate fails to compile when using futures-await 0.2.0-alpha

### ISSUE THREAD

**Issue by y-ich** [alexcrichton/futures-await#75]
Hi.
Sorry, I may be confused.

My app succeeds to compile when using futures-await 0.1.0, but when updating it to 0.2.0-alpha, fails to compile.
Actually, the app uses the crate stdweb, that uses custom derive, and compiling stdweb fails.

```
    |
109 | #[derive(Clone, Debug, PartialEq, Eq, ReferenceType)]
    |                                       ^^^^^^^^^^^^^ Could not find `stdweb` in `{{root}}`
...
error: cannot find macro `__js_raw_asm!` in this scope
   --> /Users/yuji/.cargo/registry/src/github.com-1ecc6299db9ec823/stdweb-0.4.2/src/webapi/events/socket.rs:211:39
    |
211 | #[derive(Clone, Debug, PartialEq, Eq, ReferenceType)]
    |                                       ^^^^^^^^^^^^^
    |
    = help: have you added the `#[macro_use]` on the module/import?
```

Are there any possibilities for futures-await to cause to fail compilation of other crates?
Thanks.

**Comment by withoutboats** [comment]
Possibly when you upgraded to 0.2 your lockfile changed, and there was a breaking change in stdweb.

**Comment by y-ich** [comment]
@withoutboats san, thank you for your comment.

I removed the Cargo.lock file and tried compiling again but failed.
I found that Cargo.lock includes both futures 0.1.18 and futures 0.2.0-alpha though it causes or not.
